### ISSUE TITLE
Integration with Lightning Flash Task

### ISSUE THREAD

**Issue by tchaton** [ml-tooling/opyrator#14]
**Feature description:

 
Dear People from opyrator,

Absolutely awesome framework !

At Pytorch Lightning, we are working on a tasks based framework called LightningFlash: https://github.com/PytorchLightning/lightning-flash.
It would be great to collaborate and make them available throught opyrator.

So people can train, finetune, and predict from the UI, play with the transforms and visualise them etc ...

Best,
T.C

**Problem and motivation:**

**Is this something you're interested in working on?**

**Comment by LukasMasuch** [comment]
@tchaton Thanks for the feedback! Lightning-flash looks awesome, I will take a closer look and maybe include an initial demo with lightning-flash within the playground :)
