### ISSUE TITLE
Starting the server 

### ISSUE THREAD

**Issue by 17341** [ml-tooling/opyrator#16]
Hello,

I tried to run the basic function,

      from pydantic import BaseModel
      
      class Input(BaseModel):
          message: str
      
      class Output(BaseModel):
          message: str
      
      def hello_world(input: Input) -> Output:
          """Returns the `message` of the input data."""
          return Output(message=input.message)

and got this error:  **'PYTHONPATH' is not recognized as an internal command or external, an executable program or a batch file.**

**Comment by raethlein** [comment]
Hey @17341 , the `PYTHONPATH` variable is used [at this line](https://github.com/ml-tooling/opyrator/blob/f9b54c3864a8ef9d2d3b195a600e70420001aca1/src/opyrator/ui/streamlit_ui.py#L47), although it should not be treated as a program. What OS are you using? If you use a Windows machine, I guess that the referenced line might cause the problem as the `:` probably should be a `;` for the concatentation.

**Comment by adegard** [comment]
Hello, 
I have the same issue trying to launch text generator example:
PS C:\Users\degar\opyrator\examples\generate_text> opyrator launch-ui app:generate_text --port 8051
'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file.

I'm on Windows 10

**Comment by raethlein** [comment]
The error on Windows machines should be fixed in the new version (`pip install --upgrade opyrator`)!
