### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by dmlls** [ml-tooling/opyrator#19]
**Describe your request:**

The README mentions ["Audio Sep**e**ration"](https://github.com/ml-tooling/opyrator#audio-seperation) (also appears in the screenshot located below), but as I far as I understand it should be Audio Sep**a**ration.

Anyway, just a tiny little issue for an otherwise great project :)

**Comment by raethlein** [comment]
Good catch :) Thanks for reporting it and thanks for the feedback
