### ISSUE TITLE
Cross-Origin Request

### ISSUE THREAD

**Issue by 17341** [ml-tooling/opyrator#23]
Hi,

I am getting the 405 Method not allowed error when trying to send data from a frontend app, is there any way or option to enable the Cross-Origin Request ?

![image](https://user-images.githubusercontent.com/47971960/116324033-9bd5bc00-a7bf-11eb-81d8-ddb76ffa6100.png)

Thanks,

**Comment by LukasMasuch** [comment]
Thanks for reporting :) I just pushed out a small fix: `pip install --upgrade opyrator`. I hope it fixes your issue!
