### ISSUE TITLE
multiple models

### ISSUE THREAD

**Issue by sevenold** [ml-tooling/opyrator#25]
Can I run multiple models ?

```bash

opyrator launch-ui test:mul_models

```

**Comment by LukasMasuch** [comment]
@sevenold Do you mean multiple functions/operations? With the current version, every function requires a dedicated UI server. However, we are currently exploring ways on allowing multiple functions with the same UI/API server.

**Comment by sevenold** [comment]
Okay, looking forward to this solution and Demo.
