### ISSUE TITLE
Can't get hello_world to work

### ISSUE THREAD

**Issue by Bandit253** [ml-tooling/opyrator#27]
**Hello World no go:**

**Technical details:**
I have followed the instructions on the Getting Started page, no go
[https://github.com/ml-tooling/opyrator#getting-started](url)

Created the file and run as instructed but I get this...
`2021-05-01 10:16:31.675 An update to the [server] config option section was detected. To have these changes be reflected, please restart streamlit.`
![image](https://user-images.githubusercontent.com/9003261/116765274-b29e3c00-aa67-11eb-9f44-b81f0fd88465.png)

I ran "`streamlit hello`"and that is working fine 
![image](https://user-images.githubusercontent.com/9003261/116765349-f85b0480-aa67-11eb-8f5c-e1526c1fb989.png)

- Host Machine OS : Windows 10
- python : 3.9.4

I wonder if it is the very new version of python?

I am open to being stupid, that's OK, but this looks pretty cool and I want it to work.

**Comment by LukasMasuch** [comment]
@Bandit253 Sorry for the trouble and thanks for reporting the issue. We had a few issues with Windows 10, maybe this is related. 

The error seems to indicate that the `hello_world` function could not be found in the `my_opyrator` module/script. Can you check again if the namings are correct? And did you execute this command from the folder of the `my_opyrator` script: `opyrator launch-ui my_opyrator:hello_world`? 

There is also one PR which might be related: https://github.com/ml-tooling/opyrator/pull/26

**Comment by LukasMasuch** [comment]
@Bandit253 Update: I just tried it with Windows 10 and Python 3.9. Unfortunately, I wasn't able to reproduce the issue. I just pushed out a new release including a fix for Window 10, maybe this fixes your issue as well: `pip install -U opyrator`

**Comment by Bandit253** [comment]
@LukasMasuch  don't be sorry, I thank you for any assistance.

I have tried your suggestion of upgrading alas no luck and no change to the result.
One thing I noticed when I did the update, I got this as the first line 
`WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>`

I thought I should do a `pip freeze` for reference
altair==4.1.0
argon2-cffi==20.1.0
astor==0.8.1
astroid==2.5.3
async-generator==1.10
attrs==20.3.0
autobahn==21.3.1
backcall==0.2.0
base58==2.1.0
bleach==3.3.0
blinker==1.4
cachetools==4.2.2
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
click-plugins==1.1.1
cligj==0.7.1
colorama==0.4.4
cryptography==3.4.7
cycler==0.10.0
dateparser==1.0.0
decorator==5.0.7
defusedxml==0.7.1
entrypoints==0.3
fastapi==0.63.0
Fiona @ file:///D:/Chrome_DOWNLOADS/Fiona-1.8.19-cp39-cp39-win_amd64.whl
GDAL @ file:///D:/Chrome_DOWNLOADS/GDAL-3.2.2-cp39-cp39-win_amd64.whl
geopandas==0.9.0
gitdb==4.0.7
GitPython==3.1.14
h11==0.12.0
hyperlink==21.0.0
idna==2.10
ipykernel==5.5.3
ipython==7.22.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort==5.8.0
jedi==0.18.0
Jinja2==2.11.3
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
lazy-object-proxy==1.6.0
loguru==0.5.3
MarkupSafe==1.1.1
matplotlib==3.4.1
mccabe==0.6.1
mistune==0.8.4
munch==2.5.0
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.3.0
numpy==1.20.2
opyrator==0.0.11
packaging==20.9
pandas==1.2.3
pandocfilters==1.4.3
parso==0.8.2
pickleshare==0.7.5
Pillow==8.2.0
plotly==4.14.3
prometheus-client==0.10.1
prompt-toolkit==3.0.18
protobuf==3.15.8
pycparser==2.20
pydantic==1.8.1
pydeck==0.6.2
Pygments==2.8.1
pylint==2.7.4
pyparsing==2.4.7
pyproj==3.0.1
PyQt5==5.15.2
pyqt5-plugins==5.15.2.2.1.0
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.1
pyqt5-tools==5.15.2.3.0.2
pyrsistent==0.17.3
python-dateutil==2.8.1
python-dotenv==0.17.0
pytz==2021.1
pywin32==300
pywinpty==1.0.1
pyzmq==22.0.3
qt5-applications==5.15.2.2.1
qt5-tools==5.15.2.1.0.1
regex==2021.4.4
requests==2.25.1
retrying==1.3.3
Rtree @ file:///D:/Chrome_DOWNLOADS/Rtree-0.9.7-cp39-cp39-win_amd64.whl
scipy==1.6.2
Send2Trash==1.5.0
Shapely==1.7.1
six==1.15.0
smmap==4.0.0
starlette==0.13.6
streamlit==0.81.0
termcolor==1.1.0
terminado==0.9.4
testpath==0.4.4
toml==0.10.2
toolz==0.11.1
tornado==6.1
traitlets==5.0.5
txaio==21.2.1
typer==0.3.2
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.26.4
uvicorn==0.13.4
validators==0.18.2
watchdog==2.0.3
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
win32-setctime==1.0.3
wrapt==1.12.1

I upon seeing that I think I might try a `venv`, I'll let you know how I go

**Comment by Bandit253** [comment]
Alas no good :(

**Comment by Bandit253** [comment]
Been away for a couple of days, I just tried again, no apparent change done by me but it worked

Now I can play, thanks
