### ISSUE TITLE
I want to know how to get response of POST request in running 'launch-ui'

### ISSUE THREAD

**Issue by dleunji** [ml-tooling/opyrator#30]
Hi. 
It is very useful to access Swagger UI by `opyrator launch-api ~`
But I need to use Swagger API when I'm running `opyrator launch-ui`.  I edited the /openapi.json by indicating server url. 
I tried a lot by adding `/call` behind the server url but it doesn't work..
`403 Forbidden` error just appears to me.
Could you let me how to get response of POST request in running 'launch-ui'?

**Comment by raethlein** [comment]
Hey @dleunji, the best approach right now would be to start a UI instance and an API instance in parallel as the streamlit ui does not expose a REST API but communicates with the frontend via a websocket connection.

**Comment by dleunji** [comment]
Thank you for your kind explanation:)
