### ISSUE TITLE
Allow custom h1 titles, page titles and favicons

### ISSUE THREAD

**Issue by cerob** [ml-tooling/opyrator#31]
**Feature description:**

Opyrator inserts its name to every project titles and does not allow a change. However, this is undesired and there should be an alternative place to give credits. Like on the footer, as streamlit does.

**Problem and motivation:**

The cause of behavior is on [src/opyrator/ui/streamlit_ui.py](https://github.com/ml-tooling/opyrator/blob/489ff44d84e1176d96240abbe89bdd8151f3574b/src/opyrator/ui/streamlit_ui.py) file, line 27:

```python
st.set_page_config(page_title="Opyrator", page_icon=":arrow_forward:")
```

and lines 828-830:

```python
    title = opyrator.name
    if "opyrator" not in opyrator.name.lower():
        title += " - Opyrator"
```

Since streamlit allows page config to be set once, there is no way but altering the library code manually.

An example:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/10361223/116945494-7b56a780-ac80-11eb-8e23-4ddaf0e74eb3.png">

This over-branding behavior should change. A footer reference text along with uri is enough, as people are quite used to see credits at the end of the page.

**Is this something you're interested in working on?**

Yes

Thanks.

**Comment by lukasmasuch** [comment]
@cerob Thanks for the suggestion! I removed the Opyrator suffix from the h1 title in the most recent release. And configuration options for the page title and icon will be part of an upcoming release.
