### ISSUE TITLE
Cannot use with colab?

### ISSUE THREAD

**Issue by Adarsh-Vemali** [ml-tooling/opyrator#34]
I had to change the port to 8070 as it said port 8080(default provided) is busy.
On this port in colab it shows that it is running but it doesn't open up in the browser. Firewall is off. I am using Google Colab on Chrome on Mac. 
 
![image](https://user-images.githubusercontent.com/68332419/117812418-6204bb00-b27f-11eb-93da-c037301ff7e0.png)
![image](https://user-images.githubusercontent.com/68332419/117812369-574a2600-b27f-11eb-8b9e-debb864459f8.png)

**Comment by raethlein** [comment]
Hey @Adarsh-Vemali, the IP address `0.0.0.0` is pointing to your own computer, while running Opyrator in Colab would require an URL pointing to the Colab server. I am not that familiar with starting web servers on a Colab instance and I might be wrong, but based on my brief tryout it looks like you need to use a service such as [ngrok](https://ngrok.com) to access any server started on Colab (I have tried it and with ngrok, for example, you can access the service). Hence, this is nothing Opyrator-specific.

**Comment by Adarsh-Vemali** [comment]
Hi @raethlein thank you for the reply. Yes, ngrok with fastAPI works like a charm.
