### ISSUE TITLE
Upload timeseries as csv or excel files.

### ISSUE THREAD

**Issue by meteoDaniel** [ml-tooling/opyrator#39]
Dear guys, 

 I am interested in using opyrator. In our use case we would like to upload timeseries data in csv or excel files. 

Is this supported?
And If not, can you recommend tools that are able to read generic csv files that can be added to opyrator?

Thanks a lot for discussing

Daniel

**Comment by raethlein** [comment]
Hey @meteoDaniel, sorry for the delayed answer!  I am not sure whether I understood the question correctly, but in case you would like to upload a csv / excel file to the opyrator function, you should be able to define the input as in the following example:

```python
from opyrator.components.types import FileContent
from pydantic import BaseModel, Field, validator


class Input(BaseModel):
    excel_file: FileContent = Field(
        ...,
        mime_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )


class Output(BaseModel):
    excel_file: FileContent = Field(
        ...,
        mime_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )


def return_file(input: Input) -> Output:
    return Output(excel_file=input.excel_file.as_bytes())
```

I copied the code from [this issue](https://github.com/ml-tooling/opyrator/issues/29#issuecomment-831907716) which might provide some more context. I hope this helps :)
