### ISSUE TITLE
Finalize docker export capabilities

### ISSUE THREAD

**Issue by LukasMasuch** [ml-tooling/opyrator#4]
**Feature description:**

Finalize capabilities to export an opyrator to a Docker image. 

The export can be executed via command line:

```bash
opyrator export my_opyrator:hello_world --format=docker my-opyrator-image:latest
```

_💡 The Docker export requires that Docker is installed on your machine._

After the successful export, the Docker image can be run as shown below:

```bash
docker run -p 8080:8080 my-opyrator-image:latest
```

Running your Opyrator within this Docker image has the advantage that only a single port is required to be exposed. The separation between UI and API is done via URL paths: `http://localhost:8080/api` (API); `http://localhost:8080/ui` (UI). The UI is automatically configured to use the API for all function calls.

**Comment by dleunji** [comment]
Hi. I'm using this Opyrator, and want to deploy my project in a Docker image. So I tried the command line as you noticed 
But I only got a message.
`[WIP] This feature is not finalized yet. You can track the progress and vote for the feature here: https://github.com/ml-tooling/opyrator/issues/4` :(
Is it really finalized?

**Comment by LukasMasuch** [comment]
@dleunji the Docker export is not ready yet for release :( But we have prioritized this feature and will update this issue as soon as it is ready for usage.

**Comment by amitmtrn** [comment]
Hi, I want to collaborate on this issue, can you tell me if the logic for exporting the docker would be acceptable?
1. `pip freeze` to a requirements file
2. create docker file `from` python
3. copy the opyrator file and the requirements (from the freeze)
4. pip install the requirements (on the docker file)
5.  `opyrator launch-ui` and `opyrator-launch-api` (2 ports open on the docker `8080` and `8051`)
6. dump the docker image

**Comment by raethlein** [comment]
Hey @amitmtrn, thanks for your thoughts! I think this looks like a good approach and  looks like it would be worth trying out :)  In the future we could discuss whether it could be better to have an official opyrator image (step 2) instead of using the python base image.

**Comment by kris-farr** [comment]
Any updates on this, please?
