### ISSUE TITLE
Error parsing Markdown or HTML in this string: SVG not showing bugs

### ISSUE THREAD

**Issue by Changwanseo** [ml-tooling/opyrator#40]
**Describe the bug:**

Error parsing Markdown or HTML in this string: 
the above error occurs when trying to show svg result image, and svg image not showing or downloading

I'm not used to be in web programming and pydantic models, so if I did something wrong,
you could just say "study more!" and ignore it  

Thank you

**Expected behaviour:**

svg image should be shown

**Steps to reproduce the issue:**

Here is my code

```python
from pydantic import BaseModel, Field
from opyrator.components.types import FileContent
import time

import time
import os, subprocess, shutil

from Bio import SeqIO

from ete3 import Tree, TreeStyle, NodeStyle, TextFace
import pandas as pd
import copy


class Input(BaseModel):
  tree: str = Field(
    ...,
    title="Tree Input",
    description="Copy your newick tree format"
  )
  
  percent_identity: float = Field(
    order = 0,
    description= "Percent identity, should be lower than 100, 99 ~ 99.6 recommended"
  )


class Output(BaseModel):
  image_file: FileContent = Field(..., mime_type="image/svg+xml")


def flatten(tree, accession, percent_identity=99):
	cutoff = float((100-percent_identity)/2)
	t = Tree(tree)
	ts = TreeStyle()
	#ts.scale = 100
	#ts.show_branch_length = True
	ts.allow_face_overlap = True

	name_list = []
	dict_trees = {}

	for leaf in t:
		name_list.append(leaf.name)
		dict_trees[leaf.name] = 0

	cnt = 1

	colors = ["#fbb4ae",
	"#b3cde3",
	"#ccebc5",
	"#decbe4",
	"#fed9a6",
	"#ffffcc",
	"#e5d8bd",
	]

	for node in t.traverse():
		node.img_style["size"]=2

	def go_down(node, dist):
		color = colors[cnt%len(colors)]
		for leaf in node:
			branch_sum = 0
			new_leaf = leaf
			while(new_leaf!=node):
				try:
					branch_sum += new_leaf.dist
					new_leaf = new_leaf.up
				except:
					break
			if branch_sum < cutoff:
				dict_trees[leaf.name] = cnt

	def go_up(node, dist):
		if not(node.is_root()):
			if dist+node.up.dist < cutoff: # more way to go up
				go_up(node.up, dist+node.up.dist)
			else:
				go_down(node.up, 0)

	for name in name_list:
		color = colors[cnt%len(colors)]
		if dict_trees[name] == 0: # if not node has already searched
			node = t.search_nodes(name=name)[0]
			dict_trees[name] = cnt
			go_up(node, node.dist)
			cnt += 1

	for name in name_list:
		#print(name)
		node = t.search_nodes(name=name)[0]
		cnt = dict_trees[name]
		color = colors[cnt%len(colors)]
		node.img_style["bgcolor"] = color
		back = TextFace(f"group {cnt}")
		blank = TextFace(f"       ")
		node.add_face(blank,column=1,position="branch-right")
		node.add_face(back,column=2,position="branch-right")

	t.render(f"{accession}.svg",tree_style=ts)
	dict_new = {"leaf":[],"group":[]}
	for key in dict_trees.keys():
		dict_new["leaf"].append(key)
		dict_new["group"].append(dict_trees[key]) 

	df = pd.DataFrame(dict_new)

	df.to_excel(f"{accession}.xlsx")

def Tree_grouper(input: Input,) -> Output:

	accession = time.time()
	flatten(input.tree, accession,input.percent_identity)
	print(f"{accession}.svg")
	with open(f"{accession}.svg") as f:
		svg = f.read()
	return Output(image_file=svg)
```

(for the libraries, use [pip install biopython], [pip install ete3] and [pip install PyQt5])

Input
Tree
(TM327_Metarhizium:0.15152639840759060674,(TM369_Metapochonia:0.04593148843963373862,TM330_Pochonia:0.02745325322091625442)45:0.00107340303595512832,TM328_Metarhizium:0.09865295544240419712);

Percent identity
99

Expected output
A phylogenetic tree image

**Technical details:**

- Host Machine OS (Windows/Linux/Mac): Ubuntu 20.04
- Browser (Chrome/Firefox/Safari): Chrome

**Possible Fix:**

**Additional context:**

After the problem happens, qobject starttimer problem also happens in serverside

**Comment by raethlein** [comment]
Hey @Changwanseo, 

if you update your `Output` class to this:

```python
class Output(BaseModel):
    image_file: str = Field(...)

    def render_output_ui(self, streamlit, input) -> None:  # type: ignore
        base64_svg = base64.b64encode(self.image_file.encode('utf-8')).decode("utf-8")
        img_tag = f'<img src="data:image/svg+xml;base64,{base64_svg}"/>'
        streamlit.write(img_tag, unsafe_allow_html=True)
```

the svg image should be rendered. What it does is it inserts an `img` HTML tag which itself contains the svg image base64-encoded. Alternatively, instead of embedding the base64 data, you could let the `src` point to the previously saved svg file based on the file name. Does this solve your issue?

<img width="400" alt="Screenshot 2021-06-28 at 12 19 18" src="https://user-images.githubusercontent.com/3775781/123621008-13998480-d80b-11eb-8210-9a8e9ac95171.png">

(Btw. I edited your issue for better readability of the code. [Here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) is a guide how to add code blocks via GitHub Markdown 🙂)

**Comment by Changwanseo** [comment]
> Dear @raethlein ,

Wow it works! Thanks for your help!
