### ISSUE TITLE
Finalize production deployment capabilities

### ISSUE THREAD

**Issue by lukasmasuch** [ml-tooling/opyrator#6]
**Feature description:**

Finalize capabilities to deploy an Opyrator to a cloud platform.

Rolling out your Opyrators for production usage might require additional features such as SSL, authentication, API tokens, unlimited scalability, load balancing, and monitoring. Therefore, we provide capabilities to easily  deploy your Opyrators directly on scalable and secure cloud platforms without any major overhead.

The deployment can be executed via command line:

```bash
opyrator deploy my_opyrator:hello_world <deployment-provider> <deployment-provider-options>
```

**Comment by amit-dingare** [comment]
In the absence of this feature, is there a way to deploy this to Azure?

**Comment by Dipeshpal** [comment]
How and where we can deploy this?
Is it possible to deploy on streamlit?
What is the "deployment-provider-options" in below command-

`opyrator deploy my_opyrator:hello_world <deployment-provider> <deployment-provider-options>
`

Except cloud platform like azure etc. Is there any other platform like streamlit to deploy Opyrator UI and API apps?
